AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
