AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/*
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
